name: Sanity Check

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.x

    - name: Create output directory
      run: mkdir output

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python main.py
